knp_paginator:
  page_range: 5
  default_options:
      sort_field_name: sort           # sort field query parameter name
      sort_direction_name: direction
  template:
    pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template

