index:
    path: /
    controller: App\Controller\Articles\ArticlesController::showAll

create_article:
  path: /article/new
  controller: App\Controller\Articles\ArticlesController::articleNew

show_article:
    path: /article/{id}
    controller: App\Controller\Articles\ArticlesController::show

show_articles_by_category:
  path: /category/{id}
  controller: App\Controller\Category\CategoryController::show

show_categories_in_menu:
  path: /category/{id}
  controller: App\Controller\Category\CategoryController::showAll

comment_new:
  path: comment/{id}/new
  controller: App\Controller\Articles\ArticlesController::commentNew

logout:
  path: /logout

userbio_edit:
  path: /user/edit/{id}
  controller: App\Controller\User\UserEditController::index

api:
  prefix: /api
  resource: './routes/api_routes.yaml'

api_login_check:
  path: /api/login_check
  methods: POST

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

app.swagger_ui:
  path: /doc/api
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

search:
  path: /search
  controller: App\Controller\Search\SearchController::searchFormRenderer

search_res:
  path: /results
  methods: GET
  controller: App\Controller\Search\SearchController::searchResults





